version: '3'

services:
  db:
    image: "db"
    environment:
        SA_PASSWORD: ${SA_PASSWORD}
        ACCEPT_EULA: ${ACCEPT_EULA}
    build:
      context: .
      dockerfile: db/tools/docker/Dockerfile
    volumes:
      - mssqldata:/var/opt/mssql
    ports:
      - '1401:1401'
  api:
    image: "api"
    build:
      context: .
      dockerfile: backend/tools/docker/Dockerfile
    ports:
      - "5009:5009"
    restart: on-failure
    environment:
      - ConnectionString=Data Source=db;Initial Catalog=Expo;User Id=sa;Password=${SA_PASSWORD};Pooling=False;Max Pool Size=200;MultipleActiveResultSets=True
    depends_on: 
      - db

volumes:
  mssqldata:
  