version: '3'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
        SA_PASSWORD: "Expo123456"
        ACCEPT_EULA: "Y"
    ports:
    - '1401:1401'
  api:
    build:
      context: .
      dockerfile: backend/tools/docker/Dockerfile
    ports:
      - "5009:5009"
    environment:
      ASPNETCORE_ENVIRONMENT: "prod"
    depends_on: 
      - db
  